/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Color = { 'Red' : null } |
  { 'Blue' : null } |
  { 'Green' : null } |
  { 'White' : null };
export interface CreateOrderRequest {
  'color' : Color,
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : string,
  'customerEmail' : string,
}
export interface Order {
  'status' : OrderStatus,
  'createdAt' : Time,
  'color' : Color,
  'orderId' : OrderId,
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : string,
  'customerEmail' : string,
}
export type OrderId = string;
export type OrderStatus = { 'Delivered' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a Stripe checkout session for a FloatTime clock ($12.99 USD).
   */
  'createCheckoutSession' : ActorMethod<[Color, string, string], string>,
  'createOrder' : ActorMethod<[CreateOrderRequest], Order>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  /**
   * / Check Stripe session payment status.
   */
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];